### Регистрация

POST localhost/signUp
Content-Type: application/json

{
  "firstName" : "",
  "lastName" : "Ismagilova",
  "email" : "dinara.ismagilova.mur@gmail.com",
  "password" : "Qwerty007"
}

### Войти в аккаунт

POST localhost/login
Content-Type: application/json

{
  "email": "dinara.ismagilova.mur@gmail.com",
  "password": "Qwerty007"
}